### ISSUE TITLE
No Licence?

### ISSUE THREAD

**Issue by Romanx** [diegofrata/Generator.Equals#13]
Hey there,

I was just wondering if you intended this library to not be licenced since that implies that all rights are reserved and it can't redistribute your code without [explict permissions.](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license)

**Comment by diegofrata** [comment]
Well spotted. This was meant to be licensed under MIT License since the beginning. I have added the license now.

**Comment by Romanx** [comment]
Awesome, thanks very much for the quick fix and the excellent package.
