### ISSUE TITLE
Compiler-error with static properties

### ISSUE THREAD

**Issue by bastianeicher** [diegofrata/Generator.Equals#17]
Classes with static properties, like:

```csharp
[Equatable]
partial class Sample
{
    public string Property { get; set; }
    
    public static string StaticProperty { get; set; }
}
```

lead to a compiler error when used with `Generator.Equals`:

    Member 'Sample.StaticProperty' cannot be accessed with an instance reference; qualify it with a type name instead

As a workaround, I can mark static properties with `[IgnoreEquality]`. However, I think it would be better if Generator.Equals simply ignored them by default.

**Comment by diegofrata** [comment]
Fixed in 2.2.2.
