### ISSUE TITLE
Explicit mode

### ISSUE THREAD

**Issue by HavenDV** [diegofrata/Generator.Equals#22]
Hi. Cool generator.
I am migrating to your generator from this - https://github.com/tom-englert/Equatable.Fody. It uses Fody and explicitly defined properties to implement IEquatable. I would like to see the same mode in this generator, in which you need to explicitly specify the necessary properties.
It would also be great to think about supporting IIncrementalGenerator

**Comment by diegofrata** [comment]
@HavenDV thanks for the suggestion, it should be simple to do so. Do you want to have a go at implementing it and sending a PR? 

I imagine the easiest way is to add the `Explicit` property to the `Equatable` attribute and just ignore anything not marked with an attribute. Also we would need to add the attribute `Equals` for standard equality comparison.

**Comment by HavenDV** [comment]
Thanks for the quick response. yes I will provide PR, thanks for the initial thoughts

**Comment by HavenDV** [comment]
Another idea is to remove the runtime dependency, especially for those who don't use custom Comparers. They can be delivered explicitly (with `global::` full typepaths to avoid possible collisions).
