### ISSUE TITLE
`IEnumerable<T>` property marked by `[UnorderedEquality]` causes exception during generation

### ISSUE THREAD

**Issue by Themplarer** [diegofrata/Generator.Equals#53]
I've recently found this package and wanted to replace own reflection-based equality. I marked up classes but got no result. Building project I've got warning:
> CSC : warning CS8785: Generator 'EqualsGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Nullable object must have a value'

So, error message wasn't explanatory enough. After quite a bit of debugging, I've found out that my class contained `IEnumerable<T>` property with `UnorderedEquality` attribute. It caused NullReferenceException during generation.

I believe, it is a bug, isn't it? If so, I can provide some fix.

P.S. Thanks for your work

**Comment by diegofrata** [comment]
It would be great if you could provide me with a minimum reproduction of the issue so we can pinpoint what is causing it!

**Comment by Themplarer** [comment]
Oh, yeah, sorry, I've totally forgot to provide any code :) The repro contains the only code file - `Program.cs`:
```csharp
using Generator.Equals;

var person1 = new Person
{
    Name = "Test Guy",
    Documents = new[]
    {
        new Document
        {
            Number = "1"
        },
        new Document
        {
            Number = "5"
        }
    }
};

var person2 = new Person
{
    Name = "Test Guy",
    Documents = new[]
    {
        new Document
        {
            Number = "5"
        },
        new Document
        {
            Number = "1"
        }
    }
};

Console.WriteLine(person1 == person2);

[Equatable]
internal partial class Person
{
    public string Name { get; set; } = null!;

    [UnorderedEquality] public IEnumerable<Document> Documents { get; set; } = null!;
}

[Equatable]
internal partial class Document
{
    public string Number { get; set; } = null!;
}
```

The exception raised [here](https://github.com/diegofrata/Generator.Equals/blob/main/Generator.Equals/EqualityGeneratorBase.cs#L60) because `types` is null, since `AllInterfaces` [here](https://github.com/diegofrata/Generator.Equals/blob/main/Generator.Equals/SymbolHelpers.cs#L52) does not return the type itself

**Comment by diegofrata** [comment]
Before I go into this any further, what version of .NET are you targeting and what version are you using to compile?

**Comment by diegofrata** [comment]
Actually I can reproduce it with my local installation of .NET 7.0. Very odd!

**Comment by diegofrata** [comment]
Got a fix for it. Weird that I missed one of the most obvious cases -- using IEnumerable<T>. I guess I have a strong preference for concrete types where possible. :-)

**Comment by Themplarer** [comment]
Thanks!
