### ISSUE TITLE
Probably, the generator is not incremental

### ISSUE THREAD

**Issue by lsoft** [diegofrata/Generator.Equals#56]
I'm not sure, just for fyi

https://github.com/diegofrata/Generator.Equals/blob/main/Generator.Equals/EqualsGenerator.cs#L35

Using `Compilation` inside the generator pipeline renders it is non-incremental. Additional details is here https://github.com/zompinc/sync-method-generator/issues/20

**Comment by espenrl** [comment]
https://andrewlock.net/creating-a-source-generator-part-9-avoiding-performance-pitfalls-in-incremental-generators/

Andrew Lock wrote about this recently.
