### ISSUE TITLE
Missing XML comments on generated code

### ISSUE THREAD

**Issue by Romanx** [diegofrata/Generator.Equals#9]
Hey,

If you're using XML doc comments and have warnings enabled when they are missing the source generator gets picked up (even though you've correctly added `GeneratedCodeAttribute` which you'd expect to be skipped but isn't).

Would you be interested in either:
  - Generate inheritdoc comments for overridden methods and default comments for operators 
  - Add `#pragma warning disable 1591` to the file to avoid the warnings entirely?

I'd be happy to contribute a PR for either if it's welcomed 👍

**Comment by diegofrata** [comment]
Happy to have your PR for this. I suppose #pragma would be easier/best in
this case!

**Comment by Romanx** [comment]
Happy to do pragma although I think comments would be more dev friendly but happy to defer to your preference

**Comment by diegofrata** [comment]
@Romanx I am not really strong opinionated on either, just felt #pragma requires less coding. Happy to go with inheritdoc too. Since you're contributing it, you can pick your preferred approach!

**Comment by diegofrata** [comment]
@Romanx thanks for your PR, I have merged it and released version 2.1.2 -- should be soon available on NuGet. Hopefully that's enough to get rid of XML doc warnings.
